### ISSUE TITLE
Entries are not always pushed to Firebase

### ISSUE THREAD

**Issue by bytorbrynden** [Team-Delta-KA/KA-Contest-Judging-System#6]
The entries **are** loaded, however, they aren't always pushed to Firebase.

**Comment by bytorbrynden** [comment]
CC: @noble-mushtak
Any thoughts?

**Comment by Noble-Mushtak** [comment]
Well, my version of `ka_api.js` was only to load the entries, so I need to look more at where we're pushing them to Firebase to know what to do.

**Comment by Noble-Mushtak** [comment]
Are we doing this at `tests/project_wrapper_test.html`? In that case, I need to look more at `Backend/contest_judging_sys.js` before I can figure out what went wrong.

**Comment by Noble-Mushtak** [comment]
Also, in my app, the new `ka_api.js` is returning "All done!" before it's all done.

**Comment by Noble-Mushtak** [comment]
OK, I fixed the issue with `ka_api.js`. I'll post it here when I'm finished merging our repos.

**Comment by bytorbrynden** [comment]
Yeah, I fixed that in my version @Noble-Mushtak.

The tests for this are done in `tests/project_wrapper_test.html`... I would prefer you didn't run it though, as it'll clog up my Firebase DB.

**Comment by bytorbrynden** [comment]
Fixed this in https://github.com/Gigabyte-Giant/KA-Contest-Judging-System/commit/2651fff498fab526cf106df2916100a24d323092.

**Comment by Noble-Mushtak** [comment]
The same problem is still in `ka_api.js`. Check Slack for more info: https://team-delta-ka.slack.com/

**Comment by Noble-Mushtak** [comment]
@Gigabyte-Giant Your `ka_api.js` isn't working on `ka_api_wrapper_test.html`. Log XMLHttpRequests and check _all_ `entries`. Some will be filled, some won't. The only reason your solution worked is because Firebase waited longer for all of the entries to be filled, but the function is still returning early.

**Comment by bytorbrynden** [comment]
That's perfectly fine. Remember, the only point of `ka_api.js`, is to make it easy to get data to Firebase. Nothing else will use that.

**Comment by Noble-Mushtak** [comment]
All you've done is made it much less likely that it won't work. There's still a chance that it won't wait long enough and it will fail at getting all of the `entries`.

Also, having `setTimeout()` at all in `.getContestEntries()` is completely unnecessary. Even if it works, less code for doing the same thing is better. Look at [my `ka_api.js`](https://github.com/Gigabyte-Giant/KA-Contest-Judging-System/blob/master/Backend/ka_api.js). Here, there's clearly less code but it works without using `setTimeout()` at all because it doesn't need `setTimeout()` at all. `setTimeout()` here is simply making it return early which makes it less reliable and doesn't have any use, even if the whole system still works. There's no reason to keep `setTimeout()` in at all, even if nothing's broken.

**Comment by Noble-Mushtak** [comment]
Wait...I linked to your `ka_api.js` above. [Here's mine](https://github.com/Noble-Mushtak/KA-Contest-Judging-System/blob/master/Backend/ka_api.js).

**Comment by bytorbrynden** [comment]
I'll take a look at this in a little bit. I've got other work to take care of right now.

**Comment by bytorbrynden** [comment]
Also, your version of `getContestEntries` is out of date.

**Comment by Noble-Mushtak** [comment]
OK, I've added in the `scores` JSON property. Is there anything else I need to add in or is that up to date?

**Comment by Noble-Mushtak** [comment]
OK, I'm up to date now because I've merged our repos!
